# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'XliftSDKObjcExampleWidget' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for XliftSDKSwiftExampleWidget
  pod 'XliftSDK', '= 2.0.1'

end
